#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common


- name: install  Linux common_packages
  ansible.builtin.dnf:
          name: "{{ common_packages }}"
          state: present
  become: true        